services:
  - type: web
    name: classify-api
    runtime: docker
    plan: free
    region: singapore
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION_MS
        value: "86400000"
      - key: FRONTEND_ORIGIN
        value: https://classify-lms-g12-rossum.vercel.app
      - key: MINIO_ENDPOINT
        sync: false
      - key: MINIO_ACCESS_KEY
        sync: false
      - key: MINIO_SECRET_KEY
        sync: false
      - key: MINIO_BUCKET
        value: apptitle-files
      - key: MINIO_INITIALIZE_BUCKET
        value: "false"
      - key: MINIO_PRESIGNED_EXPIRY_SECONDS
        value: "900"
      - key: MINIO_MAX_FILE_SIZE_BYTES
        value: "52428800"
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=65 -XX:InitialRAMPercentage=20 -XX:+UseSerialGC
